# Generated by Django 2.0.5 on 2018-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('accepted_jobs', models.ManyToManyField(related_name='started_jobs', to='djangoApp.User_job')),
                ('completed_jobs', models.ManyToManyField(related_name='finished_jobs', to='djangoApp.User_job')),
                ('created_jobs', models.ManyToManyField(related_name='created_by_user', to='djangoApp.User_job')),
            ],
        ),
    ]
