# Generated by Django 2.0.5 on 2018-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accepted_jobs',
            field=models.ManyToManyField(related_name='started_jobs', to='djangoApp.User_job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_jobs',
            field=models.ManyToManyField(related_name='finished_jobs', to='djangoApp.User_job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_jobs',
            field=models.ManyToManyField(related_name='created_by_user', to='djangoApp.User_job'),
        ),
    ]
